version: '3.9'
services:

  app:
    build:
      context: ./backend
      dockerfile: dockerfilev2
    container_name: laravel_app
    ports:
      - "9200:9200"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=nom_de_votre_base
      - DB_USERNAME=nom_utilisateur
      - DB_PASSWORD=mot_de_passe
    volumes:
      - ./backend:/var/www/html
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mot_de_passe_root
      MYSQL_DATABASE: nom_de_votre_base
      MYSQL_USER: nom_utilisateur
      MYSQL_PASSWORD: mot_de_passe
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - my_network

volumes:
  db_data:


networks:
  my_network:
