version: '3.9'
services:

  app:
    build:
      context: ./backend
      dockerfile: dockerfilev2
    container_name: laravel_app
    ports:
      - "9200:9200"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./backend:/var/www/html
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:
