# Étape 1 : Installer PHP et Composer
FROM php:8.2-fpm

# Étape 2 : Installer Nginx et les dépendances supplémentaires
RUN apt-get update && apt-get install -y nginx libzip-dev unzip git && \
    docker-php-ext-install pdo pdo_mysql zip

# Étape 3 : Configuration du répertoire de travail
WORKDIR /var/www/html

# Étape 4 : Copie du code source
COPY backend/ /var/www/html

# Étape 5 : Installer les dépendances avec Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --verbose

# Étape 6 : Configurer le lien symbolique de stockage
RUN php artisan storage:link

# Étape 7 : Ajuster les permissions
RUN chmod -R 775 /var/www/html/storage && chmod -R 775 /var/www/html/public/storage
RUN chown -R www-data:www-data storage bootstrap/cache && \
    chmod -R 775 storage bootstrap/cache

# Étape 8 : Copier la configuration Nginx
COPY /backend/nginx.conf /etc/nginx/nginx.conf

# Étape 9 : Exposer le port
EXPOSE 80

# Étape 10 : Démarrer Nginx et PHP-FPM
CMD service nginx start && php-fpm
