# Utiliser une image PHP avec des outils de développement courants
FROM php:8.2-fpm

# Définir le répertoire de travail
WORKDIR /var/www/html

# Installer les extensions PHP nécessaires et Composer
RUN apt-get update && apt-get install -y libzip-dev unzip git && \
    docker-php-ext-install pdo pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier les fichiers de l'application dans le conteneur
COPY . /var/www/html

# Installer les dépendances de Laravel
RUN composer install --no-dev --optimize-autoloader

# Exposer le port 9200
EXPOSE 9200

# Démarrer Laravel avec php artisan serve sur le port 9200
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=9200"]
